### ISSUE TITLE
Cannot find module './build/default/binding'

### ISSUE THREAD

**Issue by diversario** [akdubya/rbytes#3]
Every time I clone a repo with this module in it - I get this error on start on a script. I have to `npm install rbytes` to fix it. I use a bunch of other node modules and rbytes is the only one that does this.

Complete error message:

`````` node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module './build/default/binding'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at require (module.js:351:19)
    at Object.<anonymous> (/home/user/repo/node/node_modules/rbytes/index.js:1:77)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:351:19)
    at Object.<anonymous> (/home/user/repo/node/session.js:4:14)```
``````

**Comment by marook** [comment]
I can reproduce this issue with node v0.5.8.

My workaround is:
$ cd node_modules/rbytes/build && ln -s Release default

**Comment by warfares** [comment]
@marook... thanks ... works for me, node v0.6.3

**Comment by vincentcr** [comment]
i get this error on node 0.6.5, directly from npm install on linux.

marook's workaround also works for me.

**Comment by benw** [comment]
Use node's built-in [crypto.randomBytes()](http://nodejs.org/docs/latest/api/crypto.html#randomBytes) instead.

**Comment by diversario** [comment]
Oh, nice, I didn't know it was added in the crypto module. Thanks you.

One question, though - why is it wrapped in try/catch block in the example?

**Comment by benw** [comment]
I assume for the same reason as given in the rbytes doco, that it can throw if there is insufficient entropy available.
